[[project]]
name = "seimbang.in"
desc = "Seimbang.in is a money management mobile app that leverages AI technology to help Indonesians improve their financial management. By providing personalized tips, scanning receipts with OCR, and offering simple yet effective financial advice, Seimbang.in makes building good money habits easier. Our ultimate goal is to empower users to achieve financial stability and long-term success."
tags = ["mobile-app", "bangkit-academy"]
links = [{ name = "Github", url = "https://github.com/seimbang-in" }]

[[project]]
name = "jogjatour_app"
desc = "Jogjatour is a mobile application designed to provide comprehensive information about tourist attractions in Yogyakarta, catering to students, tourists, and locals. The app aims to promote awareness of Yogyakarta's destinations while supporting local tourism businesses."
tags = ["mobile-app", "flutter"]
links = [
    { name = "Github", url = "https://github.com/shandikadav/jogjatour_app" },
]

[[project]]
name = "eresource_app"
desc = "Eresource App is a library application based on the Resource Center library at Universitas Amikom Yogyakarta. We believe the facilities provided by the Resource Center can be utilized more effectively through a mobile-based application system. This project focuses solely on the Front-End Mobile App, developed using Flutter, and is created for a competition held by IITC Universitas Amikom Purwokerto."
tags = ["mobile-app", "flutter"]
links = [
    { name = "Github", url = "https://github.com/shandikadav/eresource_app.git" },
]
